spring:
  application:
    name: quiz-app
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    hikari:
      max-lifetime: 300000
      idle-timeout: 60000
      validation-timeout: 5000
  jpa:
    show-sql: true
