spring:
  application:
    name: quiz-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 300000
      idle-timeout: 60000
      validation-timeout: 5000
  jpa:
    show-sql: true
